name: Freifunk Bremen
markdown: redcarpet
highlight: pygments

timezone: Europe/Berlin
encoding: UTF-8

future: true
permalink: /blog/:year/:month/:day/:title.html
url: http://bremen.freifunk.net

paginate: 5
paginate_path: blog/page/:num

exclude: ['CNAME']

redcarpet:
    extensions: [with_toc_data]
