name: Freifunk Bremen
description: Freifunk steht für freie Kommunikation in digitalen Datennetzen. Wir verstehen frei als öffentlich zugänglich, nicht kommerziell, im Besitz der Gemeinschaft und unzensiert.

markdown: redcarpet
highlight: pygments

timezone: Europe/Berlin
encoding: UTF-8

future: true
permalink: /blog/:year/:month/:day/:title.html
url: http://bremen.freifunk.net

paginate: 5
paginate_path: blog/page/:num

exclude: ['CNAME', 'wiki']
keep_files: ['.htaccess', 'webhook.php']

redcarpet:
    extensions: [with_toc_data]

more_sep: "&lt;!-- more --&gt;"

prose:
    rooturl: "_posts"
    media: "images"
    metadata:
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
            - name: "layout"
              field:
                  element: "hidden"
                  value: "post"
            - name: "author"
              field:
                  element: "text"
                  label: "Author"