name: Freifunk Bremen
description: Freifunk steht für freie Kommunikation in digitalen Datennetzen. Wir verstehen frei als öffentlich zugänglich, nicht kommerziell, im Besitz der Gemeinschaft und unzensiert.

gems: [jekyll-paginate]

timezone: Europe/Berlin
encoding: UTF-8

permalink: /blog/:year/:month/:day/:slug.html
url: http://bremen.freifunk.net

paginate: 5
paginate_path: blog/page/:num

exclude: ['wiki', 'README.md', 'Gemfile', 'Gemfile.lock']
keep_files: ['.htaccess', 'webhook.php', 'in_freifunk.php', 'meshviewer']

more_sep: "&lt;!-- more --&gt;"

kramdown:
    input: GFM
    hard_wrap: false

prose:
    rooturl: "_posts"
    media: "images"
    metadata:
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
            - name: "layout"
              field:
                  element: "hidden"
                  value: "post"
            - name: "author"
              field:
                  element: "text"
                  label: "Author"
            - name: "published"
              field:
                  element: "hidden"
                  value: "true"
